create table timecard.mst_user (
	user_id char(8),
	hist_no int,
	kaisya_cd char(4),
	project_cd char(6) not null,
	kengen_cd char(2) not null,
	user_pw varchar(400) not null,
	sei_kana varchar(100) not null,
	mei_kana varchar(100) not null,
	sei_kanji varchar(100) not null,
	mei_kanji varchar(100) not null,
	mail_address varchar(400),
	last_access_ts timestamp,
	last_login timestamp,
	ng_count int default 0 not null,
	token_flg int default 0 not null,
	insert_id char(8) not null,
	insert_ts timestamp default (CURRENT_TIMESTAMP) not null,
	update_id char(8) not null,
	update_ts timestamp default (CURRENT_TIMESTAMP) not null,
	primary key(user_id, hist_no)
);
